baseURL = "http://www.dabolivar.com"
title = "Daniel Bolivar"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
publishDir = "build"
theme = "minimo"

disqusShortname = "dabolivar"
googleAnalytics = "UA-112634013-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Aspiring Software Crafter @ HolidayCheck. This'll be a daily apprenticeship blog."
title404 = "Oops, there's nothing here!"

[params.assets]
favicon = "favicon.ico"
customCSS = []
customJS = []
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Daniel Bolivar"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Jan 02, 2006"
listDateFormat = "Jan 02, 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 10
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "ddanielbee" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "ddanielbee"
email = "dbolivar@holidaycheck.com"
facebook = ""
github = "ddanielbee/dabolivar"
instagram = ""
linkedin = ""
twitter = "ddanielbee"
telegram = ""
google_scholar = ""

[params.social.config]
platforms = ["codepen", "email", "github", "twitter"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
weight = -10
identifier = "home"
url = "/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
